# Generated by Django 2.2 on 2019-09-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_lc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lc',
            options={'ordering': ['-created'], 'verbose_name_plural': 'LCs'},
        ),
        migrations.RenameField(
            model_name='lc',
            old_name='lc_no',
            new_name='lc_number',
        ),
        migrations.CreateModel(
            name='BIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bil_number', models.CharField(max_length=100, unique=True)),
                ('shipping_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bils', to='application.LC')),
            ],
            options={
                'verbose_name_plural': 'BILs',
                'ordering': ['-created'],
            },
        ),
    ]
